spring.datasource.hikari.connectionTimeout: 20000
spring.datasource.hikari.maximumPoolSize: 5
spring.datasource.url: jdbc:postgresql://localhost:5432/data_exchanges
spring.datasource.username: postgres
spring.datasource.password: 123
spring.datasource.driver-class-name: org.postgresql.Driver
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oapnb9qhoX67oV7e5d6
            client-secret: SQ9ApjPxSv6R4ERuaE6Jg49AzF1-1ZejNpMG0Cbr
        provider:
          okta:
            authorization-uri: https://dev-68877762.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-68877762.okta.com/oauth2/default/v1/token
            user-info-uri: https://dev-68877762.okta.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-68877762.okta.com/oauth2/default/v1/keys








